"""
Uncertainty computation module for MSXplain.

This module provides functions to compute voxel-level, lesion-level, and patient-level
uncertainty measures for MS lesion segmentation predictions from ensemble models.
"""

import os
import numpy as np
import pandas as pd
import nibabel as nib
from scipy import special
from joblib import Parallel, delayed
from functools import partial
import matplotlib.pyplot as plt
import scipy.stats as stats
import logging

# Import local modules
from .transforms import get_cc_mask, process_probs
from .data_handling import NpzDataset

logger = logging.getLogger(__name__)


# ============================================================================
# Helper Functions for Uncertainty Measures
# ============================================================================

def intersection_over_union(mask1, mask2):
    """Compute IoU for 2 binary masks.
    
    Args:
        mask1 (np.ndarray): First binary mask
        mask2 (np.ndarray): Second binary mask (must have same dimensions as mask1)
    
    Returns:
        float: Intersection over Union value (1.0 when both masks are empty)
    """
    intersection = np.sum(mask1 * mask2)
    union = np.sum(mask1 + mask2 - mask1 * mask2)
    if union == 0:
        return 1.0
    return intersection / union


def entropy_of_expected(probs, epsilon=1e-10):
    """Compute entropy of expected probabilities (voxel-level uncertainty).
    
    Args:
        probs (np.ndarray): Array of shape [num_models, num_voxels_X, num_voxels_Y, num_voxels_Z, num_classes]
        epsilon (float, optional): Small value to avoid -inf in logarithms. Defaults to 1e-10.
    
    Returns:
        np.ndarray: Voxel uncertainty map of shape [num_voxels_X, num_voxels_Y, num_voxels_Z]
    """
    mean_probs = np.mean(probs, axis=0)
    log_probs = -np.log(mean_probs + epsilon)
    return np.sum(mean_probs * log_probs, axis=-1)


def lesion_structural_uncertainty(cc_mask: np.ndarray, ens_pred_multi: np.ndarray):
    """Compute lesion structural uncertainty for a single connected component.
    
    Args:
        cc_mask (np.ndarray): Binary lesion mask, shape [H, W, D]
        ens_pred_multi (np.ndarray): Labeled lesion masks generated by an ensemble of models, shape [M, H, W, D]
    
    Returns:
        float: Lesion structural uncertainty value (1 - mean IoU across ensemble members)
    """
    def get_max_ious_ccmasks_ens(ens_multi):
        ens_ious_ = []
        for m in range(ens_multi.shape[0]):
            max_iou = 0.0
            for intersec_label in np.unique(cc_mask * ens_multi[m]):
                if intersec_label != 0.0:
                    lesion_m = (ens_multi[m] == intersec_label).astype(float)
                    iou = intersection_over_union(cc_mask, lesion_m)
                    if iou > max_iou:
                        max_iou = iou
            ens_ious_.append(max_iou)
        return ens_ious_

    # Lesion structural uncertainty measure
    # 1 - mean IoU of connected components on the ensemble's models prediction with cc_mask
    ens_ious = get_max_ious_ccmasks_ens(ens_pred_multi)
    
    return 1 - np.mean(ens_ious)


def plot_psu_distribution(psu_data: np.ndarray, new_psu_value: float, save_path: str, x_min=0, x_max=1):
    """Plot the new patient uncertainty value (PSU) with respect to PSU distribution.
    
    Args:
        psu_data (np.ndarray): An array of PSU values from the test population
        new_psu_value (float): The new PSU value to plot
        save_path (str): Path to save the plot
        x_min (int, optional): Minimum x-axis value. Defaults to 0.
        x_max (int, optional): Maximum x-axis value. Defaults to 1.
    """
    # Estimate PDF using kernel density estimation
    kde = stats.gaussian_kde(psu_data)

    # Create a range for plotting
    if x_min is None or x_max is None:
        x_min = min(psu_data) - (max(psu_data) - min(psu_data)) * 0.1
        x_max = max(psu_data) + (max(psu_data) - min(psu_data)) * 0.1
    x_plot = np.linspace(x_min, x_max, 500)
    pdf_values = kde(x_plot)

    # Calculate percentile
    percentile = stats.percentileofscore(psu_data, new_psu_value, kind='rank')

    # Plotting
    fig, ax = plt.subplots(figsize=(10, 4))

    # Plot the filled area under the curve
    ax.fill_between(x_plot, pdf_values, color='#D5EDD2', alpha=0.8)

    # Plot the curve itself
    ax.plot(x_plot, pdf_values, color='#76BF6A', linewidth=2)

    # Add the current_x marker
    current_x_pdf_value = kde(new_psu_value)[0]
    ax.plot(new_psu_value, current_x_pdf_value, marker='o', markersize=12, 
            color='#2BBAB7', linestyle='None', zorder=5)
    ax.annotate("", xy=(new_psu_value, current_x_pdf_value), 
                xytext=(new_psu_value, current_x_pdf_value * 1.5),
                fontsize=10, ha='center')

    # Customize axes
    ax.set_yticks([])
    ax.set_yticklabels([])
    ax.set_frame_on(False)

    # Set x-axis labels to min and max of data
    ax.set_xticks([np.floor(min(psu_data)), np.ceil(max(psu_data))])
    ax.set_xticklabels([f'{int(np.floor(min(psu_data)))}', f'{int(np.ceil(max(psu_data)))}'], 
                       fontsize=12, color='#666666')

    # Title with percentage
    ax.text(0.5, 1.05, f"{int(100 - percentile)} % of patients have higher uncertainty",
            transform=ax.transAxes, fontsize=20, color='#666666',
            ha='center', va='bottom')

    plt.tight_layout()
    if save_path is not None:
        plt.savefig(save_path)
    plt.close()


# ============================================================================
# Main Script Functions
# ============================================================================

def compute_uncertainties(output_dir: str, n_samples: int, proba_threshold: float,
                         n_jobs: int = 4, l_min: int = 3, class_num: int = 1,
                         temperature: float = 1.0, probs: bool = True,
                         psu_data_filepath: str = None):
    """Compute uncertainties from NPZ ensemble predictions (programmatic API).
    
    Args:
        output_dir (str): Path to directory where uncertainties will be saved
        n_samples (int): Number of ensemble samples to use
        proba_threshold (float): Probability threshold for binary segmentation
        n_jobs (int, optional): Number of parallel workers. Defaults to 4.
        l_min (int, optional): Minimum lesion size - 1. Defaults to 3.
        class_num (int, optional): Class number for binary segmentation. Defaults to 1.
        temperature (float, optional): Temperature scaling for softmax. Defaults to 1.0.
        probs (bool, optional): Whether npz contains probabilities. Defaults to True.
        psu_data_filepath (str, optional): Path to CSV file with patient uncertainties for distribution plots.
    """
    np.random.seed(0)
    
    # Load a dataset of npz predictions
    npz_dataset = NpzDataset(pred_path=output_dir, pred_prefix='pred.npz')
    
    # Dataframe to save patient uncertainties
    pat_uncs_df = []
    
    # For each predicted npz file compute & save uncertainties
    for i_f in range(len(npz_dataset)):
        # Load data for a given patient
        data = npz_dataset[i_f]
        fn = data['filename']
        
        # Determine if we have probs or logits
        if 'pred_probs' in data:
            mems_prob = data['pred_probs'][:n_samples]  # [n_samples, H, W, D]
        elif 'pred_logits' in data:
            mems_prob = data['pred_logits'][:n_samples]
            if not probs:
                # Softmax probabilities for all models in ensemble
                mems_prob = np.stack([
                    special.softmax(s / temperature, axis=0)[class_num]
                    for s in mems_prob
                ], axis=0)
        else:
            raise ValueError(f"No 'pred_probs' or 'pred_logits' found in {fn}")
        
        assert len(mems_prob.shape) == 4, f"Expected 4D array, got shape {mems_prob.shape}"
        
        # Get the affine transformation matrix
        affine = data['affine']
        
        # Binary prediction mask from ensemble model
        ens_seg_bin = process_probs(
            prob_map=np.mean(mems_prob, axis=0),
            threshold=proba_threshold,
            l_min=l_min
        )
        
        # Save ensemble prediction
        ens_pred_file = os.path.join(output_dir, "pred.nii.gz")
        nib.Nifti1Image(ens_seg_bin.astype('float32'), affine=affine).to_filename(ens_pred_file)
        
        # Multi-labeled prediction mask from ensemble model
        ens_seg_lab = get_cc_mask(ens_seg_bin)
        
        # Labeled masks from each ensemble member
        mems_seg_bin = [
            process_probs(
                prob_map=ep,
                threshold=proba_threshold,
                l_min=l_min
            )
            for ep in mems_prob
        ]
        
        mems_seg_lab = np.stack(
            [get_cc_mask(ep) for ep in mems_seg_bin],
            axis=0
        )
        
        # Compute VOXEL uncertainty maps
        vox_uncs_mask = entropy_of_expected(
            np.concatenate(
                (np.expand_dims(mems_prob, axis=-1),
                 np.expand_dims(1. - mems_prob, axis=-1)),
                axis=-1
            )
        )
        
        # Save voxel uncertainty maps in nifti format
        vox_uncs_filepath = os.path.join(output_dir, "voxel_uncs.nii.gz")
        nib.Nifti1Image(vox_uncs_mask, affine=affine).to_filename(vox_uncs_filepath)
        
        # Compute LESION & PATIENT uncertainty maps
        if ens_seg_lab.sum() == 0:
            # No lesions predicted
            les_uncs_mask = np.zeros_like(ens_seg_lab, dtype='float32')
            pat_uncs_value = 0.0
            lesion_uncertainties = {}  # Empty dict for no lesions
            
            # Save empty lesion uncertainty map
            les_uncs_filepath = os.path.join(output_dir, "lesion_uncs.nii.gz")
            nib.Nifti1Image(les_uncs_mask, affine=affine).to_filename(les_uncs_filepath)
        else:
            cc_labels = np.unique(ens_seg_lab)
            cc_labels = cc_labels[cc_labels != 0.0]
            
            if len(cc_labels) > 0:
                with Parallel(n_jobs=n_jobs) as parallel_backend:
                    process = partial(lesion_structural_uncertainty, ens_pred_multi=mems_seg_lab)
                    
                    # Returns lists of float values, each corresponding to a connected component
                    les_uncs_list = parallel_backend(delayed(process)(
                        cc_mask=(ens_seg_lab == cc_label).astype("float")
                    ) for cc_label in cc_labels)
                
                # Create a mask and lesion uncertainties mapping
                les_uncs_mask = np.zeros_like(ens_seg_lab, dtype='float32')
                lesion_uncertainties = {}
                for cc_label, les_uncs_value in zip(cc_labels, les_uncs_list):
                    les_uncs_mask += les_uncs_value * (ens_seg_lab == cc_label).astype('float')
                    # Store lesion label and its uncertainty value
                    lesion_uncertainties[int(cc_label)] = float(les_uncs_value)
            else:
                les_uncs_mask = np.zeros_like(ens_seg_lab, dtype='float32')
                lesion_uncertainties = {}
            
            # Save lesion uncertainty maps in nifti format
            les_uncs_filepath = os.path.join(output_dir, "lesion_uncs.nii.gz")
            nib.Nifti1Image(les_uncs_mask, affine=affine).to_filename(les_uncs_filepath)
            
            # Compute PATIENT uncertainty as average IoU across ensemble members
            pat_uncs_value = 1 - np.mean([
                intersection_over_union(ens_seg_bin, mems_seg_bin[i]) 
                for i in range(n_samples)
            ])
        
        # Append patient and lesion uncertainties to the dataframe
        pat_uncs_df.append({
            "filename": fn,
            "PSU": pat_uncs_value,
            "lesion_uncertainties": lesion_uncertainties  # Maps lesion_label -> uncertainty_value
        })
        
        # Create a patient uncertainty plot if possible
        if psu_data_filepath is not None and pat_uncs_value > 0:
            try:
                # Read the data with patient uncertainties
                psu_data = pd.read_csv(psu_data_filepath, index_col=0)[["DSC-based mem_th", "set name", "hash"]]
                psu_data = psu_data[psu_data["set name"] != "ood"]["DSC-based mem_th"].values
                
                plot_psu_distribution(
                    psu_data=psu_data,
                    new_psu_value=pat_uncs_value,
                    save_path=os.path.join(output_dir, f"patient_uncertainty_distribution.png")
                )
            except Exception as e:
                logger.warning(f"Could not create PSU distribution plot for {fn}: {e}")
        
        # Save patient uncertainties dataframe after each patient is processed
        pd.DataFrame(pat_uncs_df).to_csv(
            os.path.join(output_dir, f"patient_uncs.csv")
        )
