# Docker compose file for MSXplain application
services:
  msxplain_backend:
    build: ./backend
    image: msxplain_backend:dev
    container_name: msxplain_backend
    user: "${UID:-1000}:${GID:-1000}"  # Use host user ID to avoid permission issues
    volumes:
      # Persist data
      - ./backend/files:/app/files
    ports:
      - "5000:5000"
    environment:
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
    # depends_on:
    #   - db
    restart: unless-stopped
    networks:
      - msxplain-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  msxplain_frontend:
    build: ./frontend
    image: msxplain_backend:2.0
    container_name: msxplain_frontend
    ports:
      - "3001:80"
    depends_on:
      - msxplain_backend
    restart: unless-stopped
    networks:
      - msxplain-network  

  # ohif_viewer:
  #   image: lluisb3/ohif-webapp:latest
  #   container_name: msxplain_ohif_viewer
  #   volumes:
  #     # Nginx config
  #     - ./config_ohif_orthnac/config/nginx.conf:/etc/nginx/nginx.conf
  #     # Logs
  #     - ./config_ohif_orthnac/logs/nginx:/var/logs/nginx
  #     # Let's Encrypt
  #     # - letsencrypt_certificates:/etc/letsencrypt
  #     # - letsencrypt_challenges:/var/www/letsencrypt
  #   ports:
  #     - '443:443' # SSL
  #     - '80:80' # Web
  #   depends_on:
  #     #   - keycloak
  #     - orthanc
  #   restart: on-failure
  #   networks:
  #     - msxplain-network

  orthanc:
    image: jodogne/orthanc-plugins:1.12.10
    container_name: msxplain_orthancPACS
    hostname: orthanc
    volumes:
      # Config
      - ./config_ohif_orthnac/config/orthanc.json:/etc/orthanc/orthanc.json:ro
      # Persist data
      - ./config_ohif_orthnac/volumes/orthanc-db/:/var/lib/orthanc/db/
    ports:
      - '4242:4242'
      - '8042:8042'
    restart: unless-stopped
    networks:
      - msxplain-network

networks:
  msxplain-network:
    driver: bridge

